# Generated by Django 6.0.3 on 2026-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de reception"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle demande"),
                            ("read", "Vue"),
                            ("done", "Traitee"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="statut",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=180, verbose_name="nom complet"),
                ),
                ("phone", models.CharField(max_length=80, verbose_name="telephone")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "project",
                    models.CharField(blank=True, max_length=120, verbose_name="projet"),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="type de bien"
                    ),
                ),
                (
                    "budget",
                    models.CharField(blank=True, max_length=120, verbose_name="budget"),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date souhaitee"
                    ),
                ),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="heure souhaitee"
                    ),
                ),
                (
                    "appointment_mode",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="mode de rendez-vous"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
            ],
            options={
                "verbose_name": "demande de contact",
                "verbose_name_plural": "demandes de contact",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EventIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'ajout"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="derniere modification"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Plus le nombre est petit, plus l'element apparait haut dans la page.",
                        verbose_name="ordre d'affichage",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Decochez pour cacher cet element sans le supprimer.",
                        verbose_name="visible sur le site",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Chargez une nouvelle image si vous voulez remplacer le visuel actuel.",
                        null=True,
                        upload_to="site/images/",
                        verbose_name="nouvelle image",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        help_text="Exemple: /assets/nectar-bureau.png. Laissez vide si vous chargez une nouvelle image.",
                        max_length=500,
                        verbose_name="image deja dans le site",
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=120, verbose_name="categorie"),
                ),
                ("title", models.CharField(max_length=180, verbose_name="titre")),
                ("description", models.TextField(verbose_name="description courte")),
                (
                    "bullet_points",
                    models.TextField(
                        blank=True,
                        help_text="Un detail par ligne.",
                        verbose_name="details affiches",
                    ),
                ),
            ],
            options={
                "verbose_name": "idee evenement",
                "verbose_name_plural": "idees evenement",
                "ordering": ("sort_order", "title"),
            },
        ),
        migrations.CreateModel(
            name="GuidePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'ajout"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="derniere modification"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Plus le nombre est petit, plus l'element apparait haut dans la page.",
                        verbose_name="ordre d'affichage",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Decochez pour cacher cet element sans le supprimer.",
                        verbose_name="visible sur le site",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Chargez une nouvelle image si vous voulez remplacer le visuel actuel.",
                        null=True,
                        upload_to="site/images/",
                        verbose_name="nouvelle image",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        help_text="Exemple: /assets/nectar-bureau.png. Laissez vide si vous chargez une nouvelle image.",
                        max_length=500,
                        verbose_name="image deja dans le site",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("monuments", "Monuments historiques"),
                            ("musees", "Musees"),
                        ],
                        max_length=20,
                        verbose_name="rubrique du guide",
                    ),
                ),
                ("title", models.CharField(max_length=220, verbose_name="nom du lieu")),
                ("description", models.TextField(verbose_name="description courte")),
            ],
            options={
                "verbose_name": "lieu du guide de Tanger",
                "verbose_name_plural": "lieux du guide de Tanger",
                "ordering": ("section", "sort_order", "title"),
            },
        ),
        migrations.CreateModel(
            name="NewsletterSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'inscription"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="origine"
                    ),
                ),
            ],
            options={
                "verbose_name": "inscription newsletter",
                "verbose_name_plural": "inscriptions newsletter",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'ajout"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="derniere modification"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Plus le nombre est petit, plus l'element apparait haut dans la page.",
                        verbose_name="ordre d'affichage",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Decochez pour cacher cet element sans le supprimer.",
                        verbose_name="visible sur le site",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Chargez une nouvelle image si vous voulez remplacer le visuel actuel.",
                        null=True,
                        upload_to="site/images/",
                        verbose_name="nouvelle image",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        help_text="Exemple: /assets/nectar-bureau.png. Laissez vide si vous chargez une nouvelle image.",
                        max_length=500,
                        verbose_name="image deja dans le site",
                    ),
                ),
                (
                    "transaction",
                    models.CharField(
                        choices=[("sale", "Vente"), ("rent", "Location")],
                        max_length=12,
                        verbose_name="vente ou location",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Appartement"),
                            ("commercial", "Local commercial"),
                        ],
                        max_length=20,
                        verbose_name="type de bien",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="titre de l'annonce"),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="petite ligne au-dessus du titre",
                    ),
                ),
                (
                    "residence",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="residence"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="quartier"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="adresse ou emplacement"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description courte"),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=80, verbose_name="etage"),
                ),
                (
                    "unit_number",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="numero appartement/local",
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="nombre de chambres"
                    ),
                ),
                (
                    "surface_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="surface globale en m2",
                    ),
                ),
                (
                    "surface_sold",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="surface vendue"
                    ),
                ),
                (
                    "mezzanine",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="mezzanine"
                    ),
                ),
                (
                    "project_label",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="projet client"
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="prix affiche"
                    ),
                ),
                (
                    "price_note",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="note sous le prix"
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="texte du bouton"
                    ),
                ),
            ],
            options={
                "verbose_name": "bien immobilier",
                "verbose_name_plural": "biens immobiliers",
                "ordering": ("sort_order", "title"),
            },
        ),
        migrations.CreateModel(
            name="PurplePearlPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'ajout"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="derniere modification"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Plus le nombre est petit, plus l'element apparait haut dans la page.",
                        verbose_name="ordre d'affichage",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Decochez pour cacher cet element sans le supprimer.",
                        verbose_name="visible sur le site",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Chargez une nouvelle image si vous voulez remplacer le visuel actuel.",
                        null=True,
                        upload_to="site/images/",
                        verbose_name="nouvelle image",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        help_text="Exemple: /assets/nectar-bureau.png. Laissez vide si vous chargez une nouvelle image.",
                        max_length=500,
                        verbose_name="image deja dans le site",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        editable=False,
                        max_length=120,
                        unique=True,
                        verbose_name="reference du plan",
                    ),
                ),
                (
                    "button_label",
                    models.CharField(max_length=240, verbose_name="titre du bouton"),
                ),
                (
                    "title",
                    models.CharField(max_length=240, verbose_name="titre sous l'image"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="description sous l'image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        max_length=240,
                        verbose_name="description de l'image",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan Purple Pearl",
                "verbose_name_plural": "plans Purple Pearl",
                "ordering": ("sort_order", "title"),
            },
        ),
        migrations.CreateModel(
            name="PurplePearlVisitRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de reception"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle demande"),
                            ("read", "Vue"),
                            ("done", "Traitee"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="statut",
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(max_length=120, verbose_name="type de visite"),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="date souhaitee"
                    ),
                ),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="heure souhaitee"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=180, verbose_name="nom complet"),
                ),
                ("phone", models.CharField(max_length=80, verbose_name="telephone")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                (
                    "consent",
                    models.BooleanField(
                        default=False, verbose_name="accepte d'etre contacte"
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de visite Purple Pearl",
                "verbose_name_plural": "demandes de visite Purple Pearl",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SiteContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'ajout"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="derniere modification"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Plus le nombre est petit, plus l'element apparait haut dans la page.",
                        verbose_name="ordre d'affichage",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Decochez pour cacher cet element sans le supprimer.",
                        verbose_name="visible sur le site",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Tanger, Maroc",
                        max_length=200,
                        verbose_name="adresse affichee",
                    ),
                ),
                (
                    "phone_display",
                    models.CharField(
                        default="06 75 59 92 56 / 07 73 86 35 85",
                        max_length=200,
                        verbose_name="telephones affiches",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        default="212675599256",
                        help_text="Format international sans +, par exemple 212675599256.",
                        max_length=30,
                        verbose_name="numero WhatsApp",
                    ),
                ),
                (
                    "email_display",
                    models.CharField(
                        default="info@nectar.ma / contact@nectar.ma",
                        max_length=200,
                        verbose_name="emails affiches",
                    ),
                ),
            ],
            options={
                "verbose_name": "coordonnees du site",
                "verbose_name_plural": "coordonnees du site",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date d'ajout"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="derniere modification"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Plus le nombre est petit, plus l'element apparait haut dans la page.",
                        verbose_name="ordre d'affichage",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Decochez pour cacher cet element sans le supprimer.",
                        verbose_name="visible sur le site",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        default="10/10", max_length=40, verbose_name="note affichee"
                    ),
                ),
                ("quote", models.TextField(verbose_name="avis client")),
                (
                    "client_name",
                    models.CharField(max_length=160, verbose_name="nom du client"),
                ),
                (
                    "details",
                    models.CharField(max_length=260, verbose_name="details du sejour"),
                ),
                (
                    "highlight_city_center",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez pour ajouter la mention City Center comme sur la maquette.",
                        verbose_name="mentionner City Center",
                    ),
                ),
            ],
            options={
                "verbose_name": "recommandation client",
                "verbose_name_plural": "recommandations clients",
                "ordering": ("sort_order", "client_name"),
            },
        ),
    ]
