# Generated by Django 6.0.3 on 2026-07-03 11:00

from django.db import migrations, models


PLAN_ROWS = [
    {
        "key": "facade",
        "button_label": "Façade",
        "title": "Façade",
        "description": "Plan de façade en attente.",
        "image_path": "",
        "image_3d_path": "",
    },
    {
        "key": "plan-coupe",
        "button_label": "Plan Coupe",
        "title": "Plan Coupe",
        "description": "Coupe architecturale du projet Purple Pearl.",
        "image_path": "/assets/purple-pearl/plans/plan-coupe-architectural.jpg",
        "image_3d_path": "",
    },
    {
        "key": "plan-sous-sol",
        "button_label": "Plan Sous Sol",
        "title": "Plan Sous Sol",
        "description": "Plan du sous-sol du projet Purple Pearl.",
        "image_path": "/assets/purple-pearl/plans/plan-sous-sol-architectural.jpg",
        "image_3d_path": "/assets/purple-pearl/plans/plan-sous-sol-3d.jpg",
    },
    {
        "key": "plan-rdc-bas-magasins",
        "button_label": "Plan RDC BAS - MAGASINS",
        "title": "Plan RDC BAS - MAGASINS",
        "description": "Plan du RDC bas avec les magasins.",
        "image_path": "/assets/purple-pearl/plans/plan-rdc-bas-magasins-architectural.jpg",
        "image_3d_path": "/assets/purple-pearl/plans/plan-rdc-bas-magasins-3d.jpg",
    },
    {
        "key": "plan-rdc-haut-app-mezzanine",
        "button_label": "Plan RDC HAUT - APP + mezzanine",
        "title": "Plan RDC HAUT - APP + mezzanine",
        "description": "Plan du RDC haut avec appartements et mezzanines.",
        "image_path": "/assets/purple-pearl/plans/plan-rdc-haut-app-mezzanine-architectural.jpg",
        "image_3d_path": "/assets/purple-pearl/plans/plan-rdc-haut-app-mezzanine-3d.jpg",
    },
    {
        "key": "plans-etages-1-2-3-4",
        "button_label": "Plans étages 1, 2, 3 et 4",
        "title": "Plans étages 1, 2, 3 et 4",
        "description": "Plans des étages 1, 2, 3 et 4.",
        "image_path": "/assets/purple-pearl/plans/plans-etages-1-4-architectural.jpg",
        "image_3d_path": "/assets/purple-pearl/plans/plans-etages-1-4-3d.jpg",
    },
    {
        "key": "plan-1er-retrait",
        "button_label": "Plan 1er retrait",
        "title": "Plan 1er retrait",
        "description": "Plan du premier retrait.",
        "image_path": "/assets/purple-pearl/plans/plan-1er-retrait-architectural.jpg",
        "image_3d_path": "/assets/purple-pearl/plans/plan-1er-retrait-3d.jpg",
    },
    {
        "key": "plan-2eme-retrait",
        "button_label": "Plan 2eme retrait",
        "title": "Plan 2eme retrait",
        "description": "Plan du deuxième retrait.",
        "image_path": "/assets/purple-pearl/plans/plan-2eme-retrait-architectural.jpg",
        "image_3d_path": "/assets/purple-pearl/plans/plan-2eme-retrait-3d.jpg",
    },
]


def refresh_purple_pearl_plans(apps, _schema_editor):
    PurplePearlPlan = apps.get_model("website", "PurplePearlPlan")
    keys = [plan["key"] for plan in PLAN_ROWS]

    PurplePearlPlan.objects.exclude(key__in=keys).update(is_active=False)

    for index, plan in enumerate(PLAN_ROWS, start=1):
        PurplePearlPlan.objects.update_or_create(
            key=plan["key"],
            defaults={
                "button_label": plan["button_label"],
                "title": plan["title"],
                "description": plan["description"],
                "image_path": plan["image_path"],
                "alt_text": plan["title"],
                "image_3d_path": plan["image_3d_path"],
                "image_3d_alt_text": f"{plan['title']} - Plan 3D",
                "sort_order": index,
                "is_active": True,
            },
        )


def restore_previous_purple_pearl_plans(apps, _schema_editor):
    PurplePearlPlan = apps.get_model("website", "PurplePearlPlan")
    PurplePearlPlan.objects.filter(key__in=[plan["key"] for plan in PLAN_ROWS]).update(
        is_active=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_refresh_hilton_n05_n11_albums"),
    ]

    operations = [
        migrations.AddField(
            model_name="purplepearlplan",
            name="image_3d",
            field=models.ImageField(
                blank=True,
                help_text="Chargez une nouvelle image si vous voulez remplacer le plan 3D actuel.",
                null=True,
                upload_to="site/images/",
                verbose_name="nouveau plan 3D",
            ),
        ),
        migrations.AddField(
            model_name="purplepearlplan",
            name="image_3d_alt_text",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="description du plan 3D"
            ),
        ),
        migrations.AddField(
            model_name="purplepearlplan",
            name="image_3d_path",
            field=models.CharField(
                blank=True,
                help_text="Exemple: /assets/purple-pearl/plans/plan-sous-sol-3d.jpg. Laissez vide si vous chargez une nouvelle image.",
                max_length=500,
                verbose_name="plan 3D deja dans le site",
            ),
        ),
        migrations.AlterField(
            model_name="purplepearlplan",
            name="alt_text",
            field=models.CharField(
                blank=True,
                max_length=240,
                verbose_name="description du plan architectural",
            ),
        ),
        migrations.RunPython(
            refresh_purple_pearl_plans,
            restore_previous_purple_pearl_plans,
        ),
    ]
