# Generated by Codex on 2026-07-03

from django.db import migrations
from django.db.models import Q


OLD_PLAN_KEYS = [
    "general",
    "etage1",
    "etage2",
    "etage3",
    "etage4",
    "etage5",
    "etage6",
    "facades",
]

OLD_PLAN_LABELS = [
    "1. Plan sous-sol",
    "2. Plan RDC - Locaux commerciaux",
    "3. Plan RDC haut - Locaux commerciaux",
    "3.1. Plan RDC haut - Appartements avec cour",
    "Plans des 1er, 2e, 3e et 4e étages (Appartement type 1 - 2 - 3 - 4 - 5)",
    "5. Plan 1er retrait (Appartement 1 - 2 - 3 - 4)",
    "6. Plan 2e retrait (Appartement type 1 - 2 - 3 - 4)",
    "Façades & situation",
]


def remove_old_purple_pearl_plans(apps, _schema_editor):
    PurplePearlPlan = apps.get_model("website", "PurplePearlPlan")
    PurplePearlPlan.objects.filter(
        Q(key__in=OLD_PLAN_KEYS) | Q(button_label__in=OLD_PLAN_LABELS)
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_purplepearlplan_image_3d_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_old_purple_pearl_plans, migrations.RunPython.noop),
    ]
