# Generated by Codex on 2026-07-03

from django.db import migrations


PLAN_LABELS = [
    {
        "key": "facade",
        "button_label": "Façade",
        "title": "Façade",
        "description": "Plan de façade en attente.",
    },
    {
        "key": "plan-coupe",
        "button_label": "Plan coupe",
        "title": "Plan coupe",
        "description": "Coupe architecturale du projet Purple Pearl.",
    },
    {
        "key": "plan-sous-sol",
        "button_label": "Plan sous-sol",
        "title": "Plan sous-sol",
        "description": "Plan du sous-sol du projet Purple Pearl.",
    },
    {
        "key": "plan-rdc-bas-magasins",
        "button_label": "RDC bas + magasins",
        "title": "RDC bas + magasins",
        "description": "Plan du RDC bas avec magasins.",
    },
    {
        "key": "plan-rdc-haut-app-mezzanine",
        "button_label": "RDC haut : Appartement + mezzanine",
        "title": "RDC haut : Appartement + mezzanine",
        "description": "Plan du RDC haut : appartement + mezzanine.",
    },
    {
        "key": "plans-etages-1-2-3-4",
        "button_label": "Étages 1, 2, 3 et 4",
        "title": "Étages 1, 2, 3 et 4",
        "description": "Plans des étages 1, 2, 3 et 4.",
    },
    {
        "key": "plan-1er-retrait",
        "button_label": "1er retrait",
        "title": "1er retrait",
        "description": "Plan du 1er retrait.",
    },
    {
        "key": "plan-2eme-retrait",
        "button_label": "2e retrait",
        "title": "2e retrait",
        "description": "Plan du 2e retrait.",
    },
]


def correct_purple_pearl_plan_labels(apps, _schema_editor):
    PurplePearlPlan = apps.get_model("website", "PurplePearlPlan")
    for index, plan in enumerate(PLAN_LABELS, start=1):
        PurplePearlPlan.objects.filter(key=plan["key"]).update(
            button_label=plan["button_label"],
            title=plan["title"],
            description=plan["description"],
            alt_text=plan["title"],
            image_3d_alt_text=f"{plan['title']} - Plan 3D",
            sort_order=index,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_remove_old_purple_pearl_plans"),
    ]

    operations = [
        migrations.RunPython(correct_purple_pearl_plan_labels, migrations.RunPython.noop),
    ]
