# Generated by Django 6.0.3 on 2026-07-03 12:04

from django.db import migrations, models


PLAN_UPDATES = {
    "facade": {
        "description": "Visuels 3D de la façade en effet jour et effet nuit.",
        "image_path": "",
        "alt_text": "",
        "image_3d_title": "Visuel 3D - jour",
        "image_3d_path": "/assets/purple-pearl/plans/facade-3d-jour.jpg",
        "image_3d_alt_text": "Façade - effet jour",
        "image_3d_secondary_title": "Visuel 3D - nuit",
        "image_3d_secondary_path": "/assets/purple-pearl/plans/facade-3d-nuit.jpg",
        "image_3d_secondary_alt_text": "Façade - effet nuit",
    },
    "plan-coupe": {
        "image_3d_title": "Plan 3D",
        "image_3d_path": "/assets/purple-pearl/plans/plan-coupe-3d.jpg",
        "image_3d_alt_text": "Plan coupe - Plan 3D",
        "image_3d_secondary_title": "",
        "image_3d_secondary_path": "",
        "image_3d_secondary_alt_text": "",
    },
}


def add_purple_pearl_visuals(apps, _schema_editor):
    PurplePearlPlan = apps.get_model("website", "PurplePearlPlan")
    for key, values in PLAN_UPDATES.items():
        PurplePearlPlan.objects.filter(key=key).update(**values)


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_correct_purple_pearl_plan_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="purplepearlplan",
            name="image_3d_secondary",
            field=models.ImageField(
                blank=True,
                help_text="Chargez une nouvelle image si vous voulez ajouter un deuxieme visuel 3D.",
                null=True,
                upload_to="site/images/",
                verbose_name="nouveau deuxieme visuel 3D",
            ),
        ),
        migrations.AddField(
            model_name="purplepearlplan",
            name="image_3d_secondary_alt_text",
            field=models.CharField(
                blank=True,
                max_length=240,
                verbose_name="description du deuxieme visuel 3D",
            ),
        ),
        migrations.AddField(
            model_name="purplepearlplan",
            name="image_3d_secondary_path",
            field=models.CharField(
                blank=True,
                help_text="Exemple: /assets/purple-pearl/plans/facade-3d-nuit.jpg. Laissez vide si vous chargez une nouvelle image.",
                max_length=500,
                verbose_name="deuxieme visuel 3D deja dans le site",
            ),
        ),
        migrations.AddField(
            model_name="purplepearlplan",
            name="image_3d_secondary_title",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="titre du deuxieme visuel 3D"
            ),
        ),
        migrations.AddField(
            model_name="purplepearlplan",
            name="image_3d_title",
            field=models.CharField(
                default="Plan 3D",
                max_length=120,
                verbose_name="titre du premier visuel 3D",
            ),
        ),
        migrations.RunPython(add_purple_pearl_visuals, migrations.RunPython.noop),
    ]
