# Generated by Codex on 2026-07-03

from django.db import migrations, models


def clean_facade_plan_caption(apps, _schema_editor):
    PurplePearlPlan = apps.get_model("website", "PurplePearlPlan")
    PurplePearlPlan.objects.filter(key="facade").update(
        title="",
        description="",
        alt_text="",
        image_3d_title="Visuel 3D",
        image_3d_alt_text="Visuel 3D",
        image_3d_secondary_title="Visuel 3D",
        image_3d_secondary_alt_text="Visuel 3D",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_purplepearlplan_image_3d_secondary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purplepearlplan",
            name="title",
            field=models.CharField(
                blank=True,
                max_length=240,
                verbose_name="titre sous l'image",
            ),
        ),
        migrations.RunPython(clean_facade_plan_caption, migrations.RunPython.noop),
    ]
