# Generated by Django 6.0.3 on 2026-07-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0015_clean_purple_pearl_facade_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitecontact",
            name="email_display",
            field=models.CharField(
                default="contact@nectar.ma",
                max_length=200,
                verbose_name="emails affiches",
            ),
        ),
    ]
